/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as DistrictDistrictNameRouteImport } from './routes/district/$districtName'
import { Route as DetailsLbCodeRouteImport } from './routes/details/$lbCode'
import { Route as MapDistrictDistrictNameRouteImport } from './routes/map/district/$districtName'
import { Route as MapDetailsLbCodeRouteImport } from './routes/map/details/$lbCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictDistrictNameRoute = DistrictDistrictNameRouteImport.update({
  id: '/district/$districtName',
  path: '/district/$districtName',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsLbCodeRoute = DetailsLbCodeRouteImport.update({
  id: '/details/$lbCode',
  path: '/details/$lbCode',
  getParentRoute: () => rootRouteImport,
} as any)
const MapDistrictDistrictNameRoute = MapDistrictDistrictNameRouteImport.update({
  id: '/map/district/$districtName',
  path: '/map/district/$districtName',
  getParentRoute: () => rootRouteImport,
} as any)
const MapDetailsLbCodeRoute = MapDetailsLbCodeRouteImport.update({
  id: '/map/details/$lbCode',
  path: '/map/details/$lbCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/details/$lbCode': typeof DetailsLbCodeRoute
  '/district/$districtName': typeof DistrictDistrictNameRoute
  '/data': typeof DataIndexRoute
  '/map': typeof MapIndexRoute
  '/map/details/$lbCode': typeof MapDetailsLbCodeRoute
  '/map/district/$districtName': typeof MapDistrictDistrictNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/details/$lbCode': typeof DetailsLbCodeRoute
  '/district/$districtName': typeof DistrictDistrictNameRoute
  '/data': typeof DataIndexRoute
  '/map': typeof MapIndexRoute
  '/map/details/$lbCode': typeof MapDetailsLbCodeRoute
  '/map/district/$districtName': typeof MapDistrictDistrictNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/details/$lbCode': typeof DetailsLbCodeRoute
  '/district/$districtName': typeof DistrictDistrictNameRoute
  '/data/': typeof DataIndexRoute
  '/map/': typeof MapIndexRoute
  '/map/details/$lbCode': typeof MapDetailsLbCodeRoute
  '/map/district/$districtName': typeof MapDistrictDistrictNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/details/$lbCode'
    | '/district/$districtName'
    | '/data'
    | '/map'
    | '/map/details/$lbCode'
    | '/map/district/$districtName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/details/$lbCode'
    | '/district/$districtName'
    | '/data'
    | '/map'
    | '/map/details/$lbCode'
    | '/map/district/$districtName'
  id:
    | '__root__'
    | '/'
    | '/details/$lbCode'
    | '/district/$districtName'
    | '/data/'
    | '/map/'
    | '/map/details/$lbCode'
    | '/map/district/$districtName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailsLbCodeRoute: typeof DetailsLbCodeRoute
  DistrictDistrictNameRoute: typeof DistrictDistrictNameRoute
  DataIndexRoute: typeof DataIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  MapDetailsLbCodeRoute: typeof MapDetailsLbCodeRoute
  MapDistrictDistrictNameRoute: typeof MapDistrictDistrictNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district/$districtName': {
      id: '/district/$districtName'
      path: '/district/$districtName'
      fullPath: '/district/$districtName'
      preLoaderRoute: typeof DistrictDistrictNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/$lbCode': {
      id: '/details/$lbCode'
      path: '/details/$lbCode'
      fullPath: '/details/$lbCode'
      preLoaderRoute: typeof DetailsLbCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/district/$districtName': {
      id: '/map/district/$districtName'
      path: '/map/district/$districtName'
      fullPath: '/map/district/$districtName'
      preLoaderRoute: typeof MapDistrictDistrictNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/details/$lbCode': {
      id: '/map/details/$lbCode'
      path: '/map/details/$lbCode'
      fullPath: '/map/details/$lbCode'
      preLoaderRoute: typeof MapDetailsLbCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailsLbCodeRoute: DetailsLbCodeRoute,
  DistrictDistrictNameRoute: DistrictDistrictNameRoute,
  DataIndexRoute: DataIndexRoute,
  MapIndexRoute: MapIndexRoute,
  MapDetailsLbCodeRoute: MapDetailsLbCodeRoute,
  MapDistrictDistrictNameRoute: MapDistrictDistrictNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
